apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.serviceSelectorLabels | nindent 4 }}
