name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
       # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Unit test and other verification
        uses: hypertrace/github-actions/gradle@main
        with: 
          args: check jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: unit test reports
          flags: unit
     
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: ./**/build/test-results/**/*.xml
  dependency-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Dependency Check
        uses: hypertrace/github-actions/dependency-check@main